
name: Build Chain

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - development
      - 8.*
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '.gitattributes'
      - '**.md'
      - '**.adoc'
      - '*.txt'

jobs:
  build-chain:
    concurrency:
      group: pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [11, 17]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: Maven Build
    steps:
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/kogito-pipelines/.ci/actions/long-paths@1.13.x
      - name: Java and Maven Setup
        uses: kiegroup/kogito-pipelines/.ci/actions/maven@1.13.x
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: kiegroup/kogito-pipelines/.ci/actions/build-chain@1.13.x
        with:
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          BUILD_MVN_OPTS: '-Dproductized'
      - name: Surefire Report
        uses: kiegroup/kogito-pipelines/.ci/actions/surefire-report@1.13.x
        if: ${{ always() }}
